# Getting-and-Cleaning-Data-Course-Project

## CodeBook

This file names and describes the variables, data and data transformations used in this project

### Variables created
- "Subject "  #Ranges from 1 to 30; represent the subject who performed the activity for each window sample
- "Activity_ID" # Ranges from 1 to 6; represents the activity that where performed by the subject; descriptive names of the activity are represented in the variable "Activity_Lable" 
- "Activity_Lable" # Descriptive Names for the Activity_IDs

The data for these three variables come from:
- "subject_train.txt", "subject_test.text" files, which were merged and named "Subject"
- "y_train.txt", "y_test.txt" files, which were merged and named "Activity_ID"
- "activity_lables.txt" which was used to create the conditions for an ifelse function, the variable was named "Activity_Lable" 

### Variables transferred 
- "TimeBodyAccelerometer-MeanValue-X" 
- "TimeBodyAccelerometer-MeanValue-Y" 
- "TimeBodyAccelerometer-MeanValue-Z" 
- "TimeBodyAccelerometer-StandardDeviation-X" 
- "TimeBodyAccelerometer-StandardDeviation-Y" 
- "TimeBodyAccelerometer-StandardDeviation-Z"
-  "TimeGravityAccelerometer-MeanValue-X"
-  "TimeGravityAccelerometer-MeanValue-Y" 
- "TimeGravityAccelerometer-MeanValue-Z" 
- "TimeGravityAccelerometer-StandardDeviation-X"
-  "TimeGravityAccelerometer-StandardDeviation-Y"
-  "TimeGravityAccelerometer-StandardDeviation-Z" 
- "TimeBodyAccelerometerJerk-MeanValue-X"
-  "TimeBodyAccelerometerJerk-MeanValue-Y" 
- "TimeBodyAccelerometerJerk-MeanValue-Z" 
- "TimeBodyAccelerometerJerk-StandardDeviation-X" 
- "TimeBodyAccelerometerJerk-StandardDeviation-Y" 
- "TimeBodyAccelerometerJerk-StandardDeviation-Z" 
- "TimeBodyGyroscope-MeanValue-X"
-  "TimeBodyGyroscope-MeanValue-Y"
-  "TimeBodyGyroscope-MeanValue-Z" 
- "TimeBodyGyroscope-StandardDeviation-X" 
- "TimeBodyGyroscope-StandardDeviation-Y" 
- "TimeBodyGyroscope-StandardDeviation-Z" 
- "TimeBodyGyroscopeJerk-MeanValue-X" 
- "TimeBodyGyroscopeJerk-MeanValue-Y" 
- "TimeBodyGyroscopeJerk-MeanValue-Z"
-  "TimeBodyGyroscopeJerk-StandardDeviation-X" 
- "TimeBodyGyroscopeJerk-StandardDeviation-Y"
-  "TimeBodyGyroscopeJerk-StandardDeviation-Z"
-  "TimeBodyAccelerometerMagnitude-MeanValue"
-  "TimeBodyAccelerometerMagnitude-StandardDeviation"
-  "TimeGravityAccelerometerMagnitude-MeanValue"
-  "TimeGravityAccelerometerMagnitude-StandardDeviation"
-  "TimeBodyAccelerometerJerkMagnitude-MeanValue" 
- "TimeBodyAccelerometerJerkMagnitude-StandardDeviation"
-  "TimeBodyGyroscopeMagnitude-MeanValue"
-  "TimeBodyGyroscopeMagnitude-StandardDeviation"
-  "TimeBodyGyroscopeJerkMagnitude-MeanValue"
-  "TimeBodyGyroscopeJerkMagnitude-StandardDeviation"
-  "FreuquencyBodyAccelerometer-MeanValue-X"
-  "FreuquencyBodyAccelerometer-MeanValue-Y"
-  "FreuquencyBodyAccelerometer-MeanValue-Z"
-  "FreuquencyBodyAccelerometer-StandardDeviation-X"
-  "FreuquencyBodyAccelerometer-StandardDeviation-Y"
-  "FreuquencyBodyAccelerometer-StandardDeviation-Z"
-  "FreuquencyBodyAccelerometer-MeanValueFreq-X" 
- "FreuquencyBodyAccelerometer-MeanValueFreq-Y" 
- "FreuquencyBodyAccelerometer-MeanValueFreq-Z" 
- "FreuquencyBodyAccelerometerJerk-MeanValue-X" 
- "FreuquencyBodyAccelerometerJerk-MeanValue-Y" 
- "FreuquencyBodyAccelerometerJerk-MeanValue-Z"
-  "FreuquencyBodyAccelerometerJerk-StandardDeviation-X"
-  "FreuquencyBodyAccelerometerJerk-StandardDeviation-Y"
-  "FreuquencyBodyAccelerometerJerk-StandardDeviation-Z"
-  "FreuquencyBodyAccelerometerJerk-MeanValueFreq-X"
-  "FreuquencyBodyAccelerometerJerk-MeanValueFreq-Y"
-  "FreuquencyBodyAccelerometerJerk-MeanValueFreq-Z" 
- "FreuquencyBodyGyroscope-MeanValue-X" 
- "FreuquencyBodyGyroscope-MeanValue-Y"
-  "FreuquencyBodyGyroscope-MeanValue-Z" 
- "FreuquencyBodyGyroscope-StandardDeviation-X" 
- "FreuquencyBodyGyroscope-StandardDeviation-Y" 
- "FreuquencyBodyGyroscope-StandardDeviation-Z" 
- "FreuquencyBodyGyroscope-MeanValueFreq-X" 
- "FreuquencyBodyGyroscope-MeanValueFreq-Y" 
- "FreuquencyBodyGyroscope-MeanValueFreq-Z" 
- "FreuquencyBodyAccelerometerMagnitude-MeanValue" 
- "FreuquencyBodyAccelerometerMagnitude-StandardDeviation"
-  "FreuquencyBodyAccelerometerMagnitude-MeanValueFreq" 
-  "FreuquencyBodyBodyAccelerometerJerkMagnitude-MeanValue" 
- "FreuquencyBodyBodyAccelerometerJerkMagnitude-StandardDeviation" 
- "FreuquencyBodyBodyAccelerometerJerkMagnitude-MeanValueFreq" 
- "FreuquencyBodyBodyGyroscopeMagnitude-MeanValue" "FreuquencyBodyBodyGyroscopeMagnitude-StandardDeviation" 
- "FreuquencyBodyBodyGyroscopeMagnitude-MeanValueFreq" 
- "FreuquencyBodyBodyGyroscopeJerkMagnitude-MeanValue" 
- "FreuquencyBodyBodyGyroscopeJerkMagnitude-StandardDeviation" 
- "FreuquencyBodyBodyGyroscopeJerkMagnitude-MeanValueFreq"

The data of these variables come from the "X_tain.txt" and "X_test.txt"
The names of the variables come from the "features.txt"
This set of variables were extracted from the original dataset because this project only requires the mean and standard deviation values (see run_Analysis.R for more information)
Finally the variable were adjusted to more appropriate descriptive variable names (see run_Analysis.R for more information)
